"""Initial migration

Revision ID: f20d61d4615c
Revises: 
Create Date: 2025-03-18 22:18:29.101578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20d61d4615c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_responses',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('submission_time', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('student_name', sa.String(), nullable=True),
    sa.Column('grade_level', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('openness', sa.String(), nullable=True, comment='Openness: You are willing to try new things'),
    sa.Column('conscientiousness', sa.String(), nullable=True, comment='Conscientiousness: You desire to be cautious and diligent'),
    sa.Column('agreeableness', sa.String(), nullable=True, comment='Agreeableness: You are good at interacting with people'),
    sa.Column('neuroticism', sa.String(), nullable=True, comment='Neuroticism: You tend to experience negative emotions'),
    sa.Column('mbti_result', sa.String(), nullable=True, comment='Please select your MBTI (Myers-Briggs Type Indicator) result'),
    sa.Column('has_college_major_choice', sa.Boolean(), nullable=True, comment='Do you have a clear choice of college major?'),
    sa.Column('chosen_major', sa.String(), nullable=True, comment='lease specify your chosen major'),
    sa.Column('favorite_high_school_subjects', sa.String(), nullable=True, comment='Favorite high school subjects (could be more than one, seperated by comma)'),
    sa.Column('weight_high_school_subjects', sa.Integer(), nullable=True, comment='How much do you care about your favorite subjects in high school when choosing a major? Weight'),
    sa.Column('favorite_extracurricular_activities', sa.String(), nullable=True, comment='Favorite extracurricular activities'),
    sa.Column('extracurricular_activities_weight', sa.Float(), nullable=True, comment='How much do you care about your favorite extracurricular activities in high school when choosing a major? Weight'),
    sa.Column('future_career_preference', sa.String(), nullable=True, comment='Is there any future career preference (career goal)'),
    sa.Column('existing_future_career_preferences', sa.String(), nullable=True, comment='Please indicate existing future career preferences'),
    sa.Column('future_career_preference_weight', sa.Float(), nullable=True, comment='How much do you care about your future career when choosing a major? Weight'),
    sa.Column('interested_subject_areas', sa.String(), nullable=True, comment='Your most interested subject areas (multiple choice)'),
    sa.Column('hobbies', sa.String(), nullable=True, comment='Hobbies（could be more than one, seperated by comma)'),
    sa.Column('hobbies_weight', sa.Float(), nullable=True, comment='How much do you care about your hobbies when choosing a major? Weight'),
    sa.Column('subject_strengths_high_school', sa.String(), nullable=True, comment='Subject strengths in High school (multiple choice)'),
    sa.Column('elaborate_other', sa.String(), nullable=True, comment='Please describe other'),
    sa.Column('subject_strengths_weight', sa.Float(), nullable=True, comment='The degree of concern for high school strong subjects in major selection. Weight'),
    sa.Column('award_winning_competitions', sa.Boolean(), nullable=True, comment='Is there any award-winning competitions'),
    sa.Column('award_details', sa.String(), nullable=True, comment='Please state the discipline and name of the award'),
    sa.Column('awards_weight', sa.Float(), nullable=True, comment='How much do people care about awards they have received when choosing a major? Weight'),
    sa.Column('other_academic_achievements', sa.String(), nullable=True, comment='Other academic achievements (published papers, certificates, etc.)'),
    sa.Column('achievements_weight', sa.Float(), nullable=True, comment='The degree of importance attached to other achievements in choosing a major, Weight'),
    sa.Column('parents_resources', sa.String(), nullable=True, comment='Resources that parents can provide'),
    sa.Column('elaborate_parents_resources', sa.String(), nullable=True, comment='Please Elaborate "Other"'),
    sa.Column('resources_weight', sa.Float(), nullable=True, comment='The degree of concern about the resources that parents can provide when choosing a major.Weight'),
    sa.Column('post_graduation_plan', sa.String(), nullable=True, comment='Plan after undergraduate graduation'),
    sa.Column('post_graduation_plan_weight', sa.Float(), nullable=True, comment='How much do students care about their post-graduation career path when choosing their undergraduate major? Weight'),
    sa.Column('expected_annual_income', sa.Float(), nullable=True, comment='Expected annual income range (USD)'),
    sa.Column('income_weight', sa.Float(), nullable=True, comment='How much do people care about expected annual income when choosing a major? Weight'),
    sa.Column('career_prospects_preference', sa.Boolean(), nullable=True, comment='Is there a preference for career prospects'),
    sa.Column('career_prospects_details', sa.String(), nullable=True, comment='Please indicate existing preferences for career prospects'),
    sa.Column('career_prospects_weight', sa.Float(), nullable=True, comment='The degree of concern about future career prospects when choosing a major, Weight'),
    sa.Column('financial_difficulties', sa.Boolean(), nullable=True, comment='Are there any financial difficulties'),
    sa.Column('expected_annual_tuition', sa.Float(), nullable=True, comment='Expected annual tuition and living expenses range (USD)'),
    sa.Column('preferred_study_countries', sa.String(), nullable=True, comment='List the countries you wish to study for your undergraduate degree（could be more than one, seperated by comma'),
    sa.Column('country_weight', sa.Float(), nullable=True, comment='How much do students care about the country where the university is located when choosing a major? Weight'),
    sa.Column('other_considerations', sa.String(), nullable=True, comment='Please list any other considerations or requirements (optional)'),
    sa.Column('engineering_school', sa.Integer(), nullable=True, comment='Please choose your preferences of the following majors in Engineering School—Computer Science 计算机科学'),
    sa.Column('electrical_engineering', sa.Integer(), nullable=True, comment='Electrical Engineering'),
    sa.Column('mechanical_engineering', sa.Integer(), nullable=True, comment='Mechanical Engineering'),
    sa.Column('data_science', sa.Integer(), nullable=True, comment='Data Science and Data Engineering'),
    sa.Column('civil_and_enviroment_engineering', sa.Integer(), nullable=True, comment='Civil and Environmental Engineering'),
    sa.Column('aerospace_engineering', sa.Integer(), nullable=True, comment='Aerospace Engineering'),
    sa.Column('biomedical_engineering', sa.Integer(), nullable=True, comment='Biomedical Engineering'),
    sa.Column('chemical_engineering', sa.Integer(), nullable=True, comment='Chemical Engineering'),
    sa.Column('industry_engineering', sa.Integer(), nullable=True, comment='Industrial Engineering'),
    sa.Column('math', sa.Integer(), nullable=True, comment='Please choose your preferences of the following majors in Science School—Math 数学'),
    sa.Column('physics', sa.Integer(), nullable=True, comment='Physics'),
    sa.Column('chemistry', sa.Integer(), nullable=True, comment='Chemistry'),
    sa.Column('material_science', sa.Integer(), nullable=True, comment='Material Science'),
    sa.Column('biology', sa.Integer(), nullable=True, comment='Biology'),
    sa.Column('astronomy', sa.Integer(), nullable=True, comment='Astronomy'),
    sa.Column('earth_science', sa.Integer(), nullable=True, comment='Earth Science'),
    sa.Column('social_science_economy', sa.Integer(), nullable=True, comment='Social Science Economy'),
    sa.Column('finance', sa.Integer(), nullable=True, comment='Finance'),
    sa.Column('sociology', sa.Integer(), nullable=True, comment='Sociology'),
    sa.Column('political_science', sa.Integer(), nullable=True, comment='Political Science'),
    sa.Column('organization_management', sa.Integer(), nullable=True, comment='Organization management'),
    sa.Column('psychology', sa.Integer(), nullable=True, comment='Psychology'),
    sa.Column('linguistics', sa.Integer(), nullable=True, comment='Linguistics'),
    sa.Column('literature', sa.Integer(), nullable=True, comment='Literature'),
    sa.Column('art', sa.Integer(), nullable=True, comment='Art'),
    sa.Column('music', sa.Integer(), nullable=True, comment='Music'),
    sa.Column('anthropology', sa.Integer(), nullable=True, comment='Anthropology'),
    sa.Column('archaeology', sa.Integer(), nullable=True, comment='Archaeology'),
    sa.Column('philosophy', sa.Integer(), nullable=True, comment='Philosophy'),
    sa.Column('history', sa.Integer(), nullable=True, comment='History'),
    sa.Column('gender_study', sa.Integer(), nullable=True, comment='Gender study'),
    sa.Column('culture_study', sa.Integer(), nullable=True, comment='Culture study'),
    sa.Column('choosing_major', sa.String(), nullable=True, comment='The most likely reasons for students not having a major preference or having difficulty choosing a major are'),
    sa.Column('total_score', sa.Integer(), nullable=True, comment='Total score'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_index(op.f('ix_user_responses_achievements_weight'), 'user_responses', ['achievements_weight'], unique=False)
    op.create_index(op.f('ix_user_responses_aerospace_engineering'), 'user_responses', ['aerospace_engineering'], unique=False)
    op.create_index(op.f('ix_user_responses_agreeableness'), 'user_responses', ['agreeableness'], unique=False)
    op.create_index(op.f('ix_user_responses_anthropology'), 'user_responses', ['anthropology'], unique=False)
    op.create_index(op.f('ix_user_responses_archaeology'), 'user_responses', ['archaeology'], unique=False)
    op.create_index(op.f('ix_user_responses_art'), 'user_responses', ['art'], unique=False)
    op.create_index(op.f('ix_user_responses_astronomy'), 'user_responses', ['astronomy'], unique=False)
    op.create_index(op.f('ix_user_responses_award_details'), 'user_responses', ['award_details'], unique=False)
    op.create_index(op.f('ix_user_responses_award_winning_competitions'), 'user_responses', ['award_winning_competitions'], unique=False)
    op.create_index(op.f('ix_user_responses_awards_weight'), 'user_responses', ['awards_weight'], unique=False)
    op.create_index(op.f('ix_user_responses_biology'), 'user_responses', ['biology'], unique=False)
    op.create_index(op.f('ix_user_responses_biomedical_engineering'), 'user_responses', ['biomedical_engineering'], unique=False)
    op.create_index(op.f('ix_user_responses_career_prospects_details'), 'user_responses', ['career_prospects_details'], unique=False)
    op.create_index(op.f('ix_user_responses_career_prospects_preference'), 'user_responses', ['career_prospects_preference'], unique=False)
    op.create_index(op.f('ix_user_responses_career_prospects_weight'), 'user_responses', ['career_prospects_weight'], unique=False)
    op.create_index(op.f('ix_user_responses_chemical_engineering'), 'user_responses', ['chemical_engineering'], unique=False)
    op.create_index(op.f('ix_user_responses_chemistry'), 'user_responses', ['chemistry'], unique=False)
    op.create_index(op.f('ix_user_responses_choosing_major'), 'user_responses', ['choosing_major'], unique=False)
    op.create_index(op.f('ix_user_responses_chosen_major'), 'user_responses', ['chosen_major'], unique=False)
    op.create_index(op.f('ix_user_responses_civil_and_enviroment_engineering'), 'user_responses', ['civil_and_enviroment_engineering'], unique=False)
    op.create_index(op.f('ix_user_responses_conscientiousness'), 'user_responses', ['conscientiousness'], unique=False)
    op.create_index(op.f('ix_user_responses_country_weight'), 'user_responses', ['country_weight'], unique=False)
    op.create_index(op.f('ix_user_responses_culture_study'), 'user_responses', ['culture_study'], unique=False)
    op.create_index(op.f('ix_user_responses_data_science'), 'user_responses', ['data_science'], unique=False)
    op.create_index(op.f('ix_user_responses_earth_science'), 'user_responses', ['earth_science'], unique=False)
    op.create_index(op.f('ix_user_responses_elaborate_other'), 'user_responses', ['elaborate_other'], unique=False)
    op.create_index(op.f('ix_user_responses_elaborate_parents_resources'), 'user_responses', ['elaborate_parents_resources'], unique=False)
    op.create_index(op.f('ix_user_responses_electrical_engineering'), 'user_responses', ['electrical_engineering'], unique=False)
    op.create_index(op.f('ix_user_responses_engineering_school'), 'user_responses', ['engineering_school'], unique=False)
    op.create_index(op.f('ix_user_responses_existing_future_career_preferences'), 'user_responses', ['existing_future_career_preferences'], unique=False)
    op.create_index(op.f('ix_user_responses_expected_annual_income'), 'user_responses', ['expected_annual_income'], unique=False)
    op.create_index(op.f('ix_user_responses_expected_annual_tuition'), 'user_responses', ['expected_annual_tuition'], unique=False)
    op.create_index(op.f('ix_user_responses_extracurricular_activities_weight'), 'user_responses', ['extracurricular_activities_weight'], unique=False)
    op.create_index(op.f('ix_user_responses_favorite_extracurricular_activities'), 'user_responses', ['favorite_extracurricular_activities'], unique=False)
    op.create_index(op.f('ix_user_responses_favorite_high_school_subjects'), 'user_responses', ['favorite_high_school_subjects'], unique=False)
    op.create_index(op.f('ix_user_responses_finance'), 'user_responses', ['finance'], unique=False)
    op.create_index(op.f('ix_user_responses_financial_difficulties'), 'user_responses', ['financial_difficulties'], unique=False)
    op.create_index(op.f('ix_user_responses_future_career_preference'), 'user_responses', ['future_career_preference'], unique=False)
    op.create_index(op.f('ix_user_responses_future_career_preference_weight'), 'user_responses', ['future_career_preference_weight'], unique=False)
    op.create_index(op.f('ix_user_responses_gender_study'), 'user_responses', ['gender_study'], unique=False)
    op.create_index(op.f('ix_user_responses_has_college_major_choice'), 'user_responses', ['has_college_major_choice'], unique=False)
    op.create_index(op.f('ix_user_responses_history'), 'user_responses', ['history'], unique=False)
    op.create_index(op.f('ix_user_responses_hobbies'), 'user_responses', ['hobbies'], unique=False)
    op.create_index(op.f('ix_user_responses_hobbies_weight'), 'user_responses', ['hobbies_weight'], unique=False)
    op.create_index(op.f('ix_user_responses_income_weight'), 'user_responses', ['income_weight'], unique=False)
    op.create_index(op.f('ix_user_responses_industry_engineering'), 'user_responses', ['industry_engineering'], unique=False)
    op.create_index(op.f('ix_user_responses_interested_subject_areas'), 'user_responses', ['interested_subject_areas'], unique=False)
    op.create_index(op.f('ix_user_responses_linguistics'), 'user_responses', ['linguistics'], unique=False)
    op.create_index(op.f('ix_user_responses_literature'), 'user_responses', ['literature'], unique=False)
    op.create_index(op.f('ix_user_responses_material_science'), 'user_responses', ['material_science'], unique=False)
    op.create_index(op.f('ix_user_responses_math'), 'user_responses', ['math'], unique=False)
    op.create_index(op.f('ix_user_responses_mbti_result'), 'user_responses', ['mbti_result'], unique=False)
    op.create_index(op.f('ix_user_responses_mechanical_engineering'), 'user_responses', ['mechanical_engineering'], unique=False)
    op.create_index(op.f('ix_user_responses_music'), 'user_responses', ['music'], unique=False)
    op.create_index(op.f('ix_user_responses_neuroticism'), 'user_responses', ['neuroticism'], unique=False)
    op.create_index(op.f('ix_user_responses_openness'), 'user_responses', ['openness'], unique=False)
    op.create_index(op.f('ix_user_responses_organization_management'), 'user_responses', ['organization_management'], unique=False)
    op.create_index(op.f('ix_user_responses_other_academic_achievements'), 'user_responses', ['other_academic_achievements'], unique=False)
    op.create_index(op.f('ix_user_responses_other_considerations'), 'user_responses', ['other_considerations'], unique=False)
    op.create_index(op.f('ix_user_responses_parents_resources'), 'user_responses', ['parents_resources'], unique=False)
    op.create_index(op.f('ix_user_responses_philosophy'), 'user_responses', ['philosophy'], unique=False)
    op.create_index(op.f('ix_user_responses_physics'), 'user_responses', ['physics'], unique=False)
    op.create_index(op.f('ix_user_responses_political_science'), 'user_responses', ['political_science'], unique=False)
    op.create_index(op.f('ix_user_responses_post_graduation_plan'), 'user_responses', ['post_graduation_plan'], unique=False)
    op.create_index(op.f('ix_user_responses_post_graduation_plan_weight'), 'user_responses', ['post_graduation_plan_weight'], unique=False)
    op.create_index(op.f('ix_user_responses_preferred_study_countries'), 'user_responses', ['preferred_study_countries'], unique=False)
    op.create_index(op.f('ix_user_responses_psychology'), 'user_responses', ['psychology'], unique=False)
    op.create_index(op.f('ix_user_responses_resources_weight'), 'user_responses', ['resources_weight'], unique=False)
    op.create_index(op.f('ix_user_responses_social_science_economy'), 'user_responses', ['social_science_economy'], unique=False)
    op.create_index(op.f('ix_user_responses_sociology'), 'user_responses', ['sociology'], unique=False)
    op.create_index(op.f('ix_user_responses_subject_strengths_high_school'), 'user_responses', ['subject_strengths_high_school'], unique=False)
    op.create_index(op.f('ix_user_responses_subject_strengths_weight'), 'user_responses', ['subject_strengths_weight'], unique=False)
    op.create_index(op.f('ix_user_responses_total_score'), 'user_responses', ['total_score'], unique=False)
    op.create_index(op.f('ix_user_responses_weight_high_school_subjects'), 'user_responses', ['weight_high_school_subjects'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_responses_weight_high_school_subjects'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_total_score'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_subject_strengths_weight'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_subject_strengths_high_school'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_sociology'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_social_science_economy'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_resources_weight'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_psychology'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_preferred_study_countries'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_post_graduation_plan_weight'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_post_graduation_plan'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_political_science'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_physics'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_philosophy'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_parents_resources'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_other_considerations'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_other_academic_achievements'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_organization_management'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_openness'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_neuroticism'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_music'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_mechanical_engineering'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_mbti_result'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_math'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_material_science'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_literature'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_linguistics'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_interested_subject_areas'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_industry_engineering'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_income_weight'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_hobbies_weight'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_hobbies'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_history'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_has_college_major_choice'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_gender_study'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_future_career_preference_weight'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_future_career_preference'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_financial_difficulties'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_finance'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_favorite_high_school_subjects'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_favorite_extracurricular_activities'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_extracurricular_activities_weight'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_expected_annual_tuition'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_expected_annual_income'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_existing_future_career_preferences'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_engineering_school'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_electrical_engineering'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_elaborate_parents_resources'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_elaborate_other'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_earth_science'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_data_science'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_culture_study'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_country_weight'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_conscientiousness'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_civil_and_enviroment_engineering'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_chosen_major'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_choosing_major'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_chemistry'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_chemical_engineering'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_career_prospects_weight'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_career_prospects_preference'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_career_prospects_details'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_biomedical_engineering'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_biology'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_awards_weight'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_award_winning_competitions'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_award_details'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_astronomy'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_art'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_archaeology'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_anthropology'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_agreeableness'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_aerospace_engineering'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_achievements_weight'), table_name='user_responses')
    op.drop_table('user_responses')
    op.drop_table('users')
    # ### end Alembic commands ###
