global:
  scrape_interval: "1m"

scrape_configs:
  - job_name: fastapi
    metrics_path: /metrics
    static_configs:
      - targets: ['fastapi:8000']


  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

    