name: GPT CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v6

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run tests
        run: poetry run pytest

      - name: Build Docker image
        run: docker build -t gpt-project:${{ github.sha }} .



